name: Add to Project (temporary placeholder)
on:
  workflow_dispatch:
jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: echo "Temporarily disabled; will be replaced."
