name: Node.js CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - chore/ruleset-smoke-2025-09-13
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: "22"
          cache: "npm"
      - run: npm ci
      - run: npm test
